theme: jekyll-theme-minimal
title: Adnan Saif
description: Data Scientist | ML Engineer | Data Analyst
ğŸ“ New Delhi, India  
ğŸ“§ adnansaif7474@gmail.com  
ğŸ”— [GitHub](https://github.com/adnan-saif)  
ğŸ”— [LinkedIn](https://linkedin.com/in/adnan-saif-80419224a) 
